### ISSUE TITLE
printBin for() loop should check 1 bit at a time

### ISSUE THREAD

**Issue by sturem** [xopr/gigatron-tester#1]
`gigatron-tester.ino` function `printBin` (around line 238 near end-of-file) initialises the `for()` loop incorrectly. The loop operates by using the `test` loop index to inspect each bit of the given `_var` value in turn, and write a 1 or 0 character, until the whole byte is written out. However `test` is initialised to all-1s instead of most-significant-bit-1 -- so `(_var & test)` checks too many bits on most iterations (except for the least-significant-bit, by which time there is only 1 bit set in `test`), and only works correctly if `_var==0xff`.

So this:

```
void printBin( byte _var )
{
  for ( byte test = 0xff; test; test >>= 1 )
  {
    Serial.write( (_var & test) == test ? '1' : '0');
  }
}
```

Should be this:

```
void printBin( byte _var )
{
  for ( byte test = 0x80; test; test >>= 1 )
  {
    Serial.write( (_var & test) == test ? '1' : '0');
  }
}
```

Currently printBin looks to be unused anyway, so it doesn't actually matter: but it could be useful if it worked.

**Comment by xopr** [comment]
Good find!
I didn't think anyone would use this sketch.
Fixed in commit 02fe014, together with #2
