### ISSUE TITLE
Reference https://gigatron.io/ in the description?

### ISSUE THREAD

**Issue by sturem** [xopr/gigatron-tester#2]
It would be worth referencing https://gigatron.io/ in the project description and/or README, so anyone browsing this can easily find out a bit about Gigatron TTL microcomputer -- the cool TTL-SSI/MSI-only minimal-8-bit- computer this code is designed to test!  :-)

**Comment by xopr** [comment]
Added the link together with a tiny description (the original website is far better in describing it, and to be honest, their documentation was really helpful in debugging the issues I had)

Fixed in commit 02fe014, together with #1
